# generated by Git for Windows

export PATH="/home/linuxbrew/.linuxbrew/bin":"$PATH"
export PATH="/home/linuxbrew/.linuxbrew/sbin":"$PATH"

test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
