set -x TERM xterm-256color
set -x CLOUDSDK_PYTHON python3
set -x CLOUDSDK_PYTHON_SITEPACKAGES 1
set -x HOMEBREW_FORCE_BREWED_CURL 1
set -x HOMEBREW_FORCE_BREWED_GIT 1
set -x GOPATH $HOME/go
set -x DOTNET_ROOT $HOME/.dotnet

set -x PATH $GOPATH/bin $PATH
